name: build
on: [push]
jobs:
    build-android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: chmod +x ./gradlew
            - run: ./gradlew webploader-common:build webploader-android:assembleRelease
            - uses: actions/upload-artifact@v2
              with:
                  name: artifacts
                  path: |
                      webploader-common/build/libs/webploader-common-*.jar
                      webploader-android/build/outputs/aar/webploader-android-release.aar